apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-rockergaming-s3
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /mnt/Xenon/HomeLab/RockerGaming/s3
    server: 192.168.1.110
