---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: rockergaming
  labels:
    app: minio
data:
  MINIO_ROOT_USER: c3BlY2lhbC1hY2Nlc3Mta2V5LTEyMzQ1LTY3ODkw
  MINIO_ROOT_PASSWORD: bXlBd2Vzb21lUGxlbnRpZnVsU2VjaHkvc2VjcmV0U3VwZXJTZWNyZXQva2V5Rm9vQg==

# special-access-key-12345-67890
# myAwesomePlentifulSechy/secretSuperSecret/keyFooB



BsHyGicVzrMnrL3r3
0GdlHDPxEVeqyXr4J7wqRzArUBstQ2tg3


rockergaming-api-user
rockergaming/api/secretKey