---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-rockergaming-com
  namespace: default
spec:
  secretName: lab-rockergaming-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.lab.rockergaming.com"
  dnsNames:
  - "lab.rockergaming.com"
  - "*.lab.rockergaming.com"
