---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-only-modders
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: edbz2k2@gmail.com
    privateKeySecretRef:
      name: letsencrypt-only-modders
    solvers:
    - dns01:
        cloudflare:
          email: edbz2k2@gmail.com
          apiTokenSecretRef:
            name: cloudflare-only-modders-api-token-secret
            key: api-token
      selector:
        dnsZones:
          - "onlymodders.com"
          