---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dobroveanu-cloud
  namespace: dobroveanu-cloud
spec:
  secretName: dobroveanu-cloud-tls
  issuerRef:
    name: letsencrypt-dobroveanu-cloud
    kind: ClusterIssuer
  commonName: "*.dobroveanu.cloud"
  dnsNames:
  - "dobroveanu.cloud"
  - "*.dobroveanu.cloud"
